== CUIE - Assignment 2 - TimeControl

=== Bearbeitet von

* Petra Kohler
* Karin Güdel

=== Abgabe

* Montag, 18.12.2022, 12:00 Uhr
* Die Abgabe erfolgt durch ein "Push" auf den Master-Branch Ihres GitHub-Repositories.

=== Anwendungskontext

* _Unser Time Control ist für Pflegende und Senior:innen in Altersheimen konzipiert. Von einer/einem Pflegenden kann die Zeit
für die Einnahme des nächsten Medikamentes und dessen Bezeichnung manuell eingestellt werden. Die Zeit kann entweder aus einem Dropdown
mit üblichen Zeiten für die Einnahme von Medikamenten (8:00, 12:00, 16:00; 20:00; 23.59) ausgewählt oder manuell eingestellt
werden.

Mit den Pfeiltasten (oben/unten) wird die Zeit um 15min hoch oder runter gestellt, weil Medikamente selten genauer als
Viertstunden genau eingenommen werden müssen; mit den Pfeiltasten (links/rechts) wird auf eine halbe Stunde ab- oder
aufgerundet. Mit der escape Taste wird die Zeit wieder auf 00:00 gesetzt. Mit der enter Taste wird die Zeit auf die
letzte Stunde abgerundet.
Wenn vor 17 Uhr eine Zeit auf read-only gesetzt wird, die vor der aktuellen Zeit liegt, dann blinkt der Timer,
weil die Zeit nicht korrekt sein kann: sie muss nach der aktuellen Zeit liegen. Wenn nach 17 Uhr eine Zeit eingestellt wird,
dann fällt diese Hilfestellung beim Einstellen weg, weil das nächste Medikament höchstwahrscheinlich am nächsten Tag
zu einer früheren Zeit eingenommen werden muss.

Wenn die Zeit richtig eingestellt ist, dann wird sie von den Pflegenden auf "read only" gesetzt und für den/die
Senior:in an einen gut sichtbaren Ort gestellt.

=== Initiale Schritte

* Tragen Sie ihre Namen unter "Bearbeitet von" ein.
* Pushen Sie diese Änderungen sofort ins Git-Repository (z.B. via `VCS -> Commit… -> Commit & Push`)

=== Aufgabe: BusinessControl

Entwerfen und implementieren Sie das im Unterricht besprochene BusinessControl "TimeControl" auf Basis JavaFX.

* Benutzen Sie zur Umsetzung die vorgegebene Struktur mit Control, Skin und CSS.
* Beschreiben Sie im Abschnitt 'Anwendungskontext' (siehe oben) kurz für welchen spezifischen Zweck Ihr TimeControl entworfen wurde.

Es wird empfohlen, diese Aufgabe in einem 2-er Team zu bearbeiten.

=== Bewertung

* Für 3 Punkte muss das TimeControl unter 'Anwendungskontext' kurz beschrieben werden und die im Unterricht besprochenen Mindestanforderungen an ein BusinessControl erfüllt sein.
** die aktuelle Zeit kann angezeigt und verändert werden
** die Beschriftung kann definiert werden und wird geeignet visualisiert
** auf die Statuswechsel readOnly/editable, mandatory/optional, valid/invalid, konvertierbar/nicht konvertierbar wird dynamisch reagiert
** optimale Keyboard-Unterstützung inklusive Forgiving-Format
** optimale Maus-Unterstützung innerhalb des DropDownChoosers
* 0 Punkte gibt es
** falls das Projekt nicht komplierfähig ist
** falls die Demo-Applikation bereits beim Start abstürzt
** falls der im Unterricht erarbeitete und jeweils in Teams zur Verfügung gestellte Stand nicht deutlich erkennbar verändert wurde
** für Plagiate
** falls kein aktiver Beitrag eines der beiden Teammitglieder an der Lösung erkennbar ist
** im Zweifelsfall wird ein Code-Walkthrough durchgeführt
* In Ausnahmefällen kann es dazu kommen, dass Teammitglieder unterschiedliche Punkte erhalten.


=== Bitte beachten Sie

* Falls Sie das Assignment zu zweit bearbeiten:
** tragen Sie beide Namen unter "Bearbeitet von" ein
** arbeiten Sie ausschliesslich in einem Repository
** falls sie beide Zugang zu diesem Repository wollen: tragen Sie die zweite Person als "Collaborator" ein (auf GitHub unter "Settings -> Manage access")
** löschen Sie das nicht benötigte Repository (auf GitHub unter "Settings")
** arbeiten Sie gemeinsam und gleichzeitig an den Aufgaben (Stichwort: Pair-Programming)
** https://www.it-agile.de/wissen/agiles-engineering/pair-programming/[Pair-Programming] heisst insbesondere, dass beide Teammitglieder zu gleichen Teilen aktiv in der Entwickler-Rolle sind. Einem Entwickler lediglich bei seiner Arbeit zuzuschauen ist kein Pair-Programming.
** für "Remote Pair-Programming" ist das "Code With Me"-Funktion für IntelliJ IDEA sehr zu empfehlen
** das Aufteilen und separate Bearbeiten von Teil-Aufgaben ist nicht erwünscht
* Ausdrücklich erlaubt und erwünscht ist, dass Sie sich gegebenenfalls Hilfe holen.
Nachfragen werden zum Beispiel über den im Repository integrierten
Issue Tracker oder in MS Teams gerne beantwortet.

